### ISSUE TITLE
Docs for gradle-setup should provide specific guidance for build cache on CI

### ISSUE THREAD

**Issue by 3flex** [gradle/actions#102]
I'd raised https://github.com/detekt/detekt/pull/6700 in detekt project to disable local build cache when using CI, we never really landed on whether that was a good idea or not, and it would be great if that could either be covered off in the README on setup-gradle, or if it's a bad idea, just let me know and I'll close this (and the detekt PR).

Copied from the PR:

> From https://docs.gradle.org/8.5/userguide/build_cache.html#sec:build_cache_configure:
> 
> > Gradle tries to load build outputs from the local build cache first, and
> > then tries the remote build cache if no build outputs are found. If
> > outputs are found in the remote cache, they are also stored in the local
> > cache, so next time they will be found locally.
> 
> Inversely this means that that when local cache is hit, the outputs will not be stored in the remote cache. This is not what we want on CI nodes. Forcing remote build cache only on CI means cache will be updated for every task that does not have outputs already stored in the remote cache. This ensures they're available for local dev builds.
> 
> This recent build result is from CI: https://ge.detekt.dev/s/55usta3jzxkya/timeline?toggled=WyI5Il0&view=by-type#9
> The first two tasks listed are :detekt-gradle-plugin:compileFunctionalTestKotlin and :detekt-gradle-plugin:compileTestKotlin. They were both restored from (local) cache which was restored by gradle-build-action.
> 
> This result is from my machine hours later: https://ge.detekt.dev/s/cphvzlb5tnkti/timeline?toggled=WyIzOCJd&view=by-type#38
> The same two tasks listed 2nd and 3rd were not restored from (remote) cache because they weren't stored there by the CI run.

**Comment by bigdaz** [comment]
Thanks for your question/request. Unfortunately, I/we don't have a clear answer to the question of "should local build-cache be enabled on CI". There are many different factors that can influence this decision:
- Do you have a remote cache?
- If you have a remote cache, does it have a fast connection from your GitHub Actions runners?
- If you enable local build cache, how big does the `build-cache-1` directory end up? (You can see this data in the logs if you re-run a job with debug logging enabled).
- Are you able to use [gradle-home-cache-cleanup](https://github.com/gradle/actions/tree/main/setup-gradle#remove-unused-files-from-gradle-user-home-before-saving-to-the-cache) with your workflow? (This feature relies on some hacks that can make it a bit unreliable).

In the end, I don't feel comfortable making a recommendation at this time. It's up to you to experiment and guage the impact of enabling the local build cache. I understand that this answer is not very satisfactory, but unfortunately we just don't have clear guidance to provide.

Related issues:
https://github.com/gradle/gradle/issues/17511
https://github.com/gradle/gradle/issues/17510

Once Gradle 8.8 is released, my plan is to rework the cache-cleanup functionality so that it's more robust and reliable, with a goal of enabling it by default when `v4` of this action is released. 
Having cleanup reliably enabled may mean that enabling local build cache is a good idea on CI, particular if no remote build cache is available. When the remote build cache is available, it's hard to say how restoring the `build-cache-1` directory from the GitHub Actions will compare with restoring individual cache entries from the remote cache.

We've already made some progress on issues related to cache cleanup (https://github.com/gradle/gradle/issues/28505, https://github.com/gradle/gradle/issues/28178), but you can [see here](https://github.com/gradle/actions/issues/26#issuecomment-1935280999) that there's quite a bit to go.

**Comment by 3flex** [comment]
Thank you for the detailed response and links to other issues - we have remote cache, I assume it's fast enough (it's a sponsored Develocity instance from Gradle Inc). The main issue I was trying to solve was making sure the remote cache is always primed so contributors benefit as much as possible and disabling the local cache on CI seemed the best way to achieve that. Performance on CI was a secondary consideration.

I'm hoping there's enough information to say, if remote cache is available:
1. Disabling local cache on CI will maximise utilisation of the remote cache and provide the most benefit for local builds that read from the remote cache.
2. Enabling local cache on CI is likely to result in faster builds on CI hosts but may not consistently prime the remote cache, potentially leading to slower local builds.

I just don't know if the two statements are completely accurate.

**Comment by pavlospt** [comment]
RE: CI Cache: would it ever be possible to pick different cache storages instead of the default of GitHub Actions?

**Comment by bigdaz** [comment]
> RE: CI Cache: would it ever be possible to pick different cache storages instead of the default of GitHub Actions?

I won't say never, but it's not currently on the roadmap.

**Comment by bigdaz** [comment]
> I'm hoping there's enough information to say, if remote cache is available:
> 
> 1. Disabling local cache on CI will maximise utilisation of the remote cache and provide the most benefit for local builds that read from the remote cache.
> 2. Enabling local cache on CI is likely to result in faster builds on CI hosts but may not consistently prime the remote cache, potentially leading to slower local builds.
> 
> I just don't know if the two statements are completely accurate.

I've asked around, and you're correct that disabling the local cache on CI will increase the chance of getting a remote-cache hit for a local build. The reason is a little convoluted, but what happens is:
1. The CI server does some work (e.g. compiling), and stores this result in both the local and remote caches.
2. Subsequent CI runs read the value from the local cache. 
3. Local builds will read from the remote cache on first use, but after that they read the value from local cache.
4. **Over time, the cache entry gets stale and is discarded from the remote cache**

Unfortunately, the only way to overcome this situation is to disable the local cache on CI. There's not really any way to send a 'keep-alive' signal to tell the remote cache to retain an entry, without actually getting that entry from the remote cache.
