### ISSUE TITLE
Please avoid using `v{...}` for branches

### ISSUE THREAD

**Issue by TheMrMilchmann** [gradle/actions#130]
Dependabot considers the branch `v321` to be the latest (major) version of this action and will create PRs for this version now. ([Example](https://github.com/Osmerion/OneTrickPony/pull/15)) This is correct because GH Actions can be sourced from any refs (including branches).

This is highly misleading and likely to cause issues further down the road if the branch is removed, or new major versions are considered older than 321.

**Comment by bigdaz** [comment]
Thanks for the pointer. That branch has been deleted.
Its somewhat surprising that Dependabot only looks at the branches/tags of the repository, rather than taking the actual releases into account!

**Comment by bigdaz** [comment]
> Tag deletion caused some issues but I suppose it's better than not deleting. We merged the dependabot upgrade, it worked, but wiping the tag broke CI later on.
> 
> Github releases are a non-git feature whereas tags are core git features.

There was never a `v321` _tag_, but there was a _branch_ with that name. The branch has been deleted.
I didn't realize that Dependabot would assume that branch represented a release, since branches don't necessarily indicate a permanent state in the repository (unlike tags, which are designed to be permanent markers).

**Comment by tbroyer** [comment]
GitHub Actions allow using any ref, including branches, so one could manage major versions using branches for instance, and only tagging minors (or even use branches for minors and only tagging bugfixes), rather than "retagging": https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-public-action

I suppose this is the reason Dependabot suggests branches as well.

**Comment by bigdaz** [comment]
> GitHub Actions allow using any ref, including branches, so one could manage major versions using branches for instance, and only tagging minors (or even use branches for minors and only tagging bugfixes), rather than "retagging": https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-public-action

Yep, I understand that now. It means we need to be careful about what branches we create.
