### ISSUE TITLE
The setup-gradle action should make the Gradle wrapper executable

### ISSUE THREAD

**Issue by zumbiepig** [gradle/actions#194]
The setup-gradle action should do `chmod +x ./gradlew` so you don't have to do that in another step.

**Comment by bigdaz** [comment]
This would be nice, but a bit tricky since the repository can contain any number of Gradle projects and `gradlew` scripts. We could easily `chmod` one found at the top-level, but this wouldn't work in all cases.

Is there a reason you can't simply [update the executable permissions](https://stackoverflow.com/questions/21691202/how-to-create-file-execute-mode-permissions-in-git-on-windows) of the file in the repository?

**Comment by bgalek** [comment]
`find . -name "*.sh" -exec chmod +x {} \;` should work with any gradlew path ;)

**Comment by bigdaz** [comment]
This action only works with Gradle User Home, and does not impact project files. As such, I don't think we'll be fixing this issue.

It's common practise to mark the `gradlew` file as executable in the source tree: I don't really understand how this is a security concern.
