### ISSUE TITLE
[Question] Inconsistent gradle configuration exclusion results

### ISSUE THREAD

**Issue by Pil0tXia** [gradle/actions#198]
I want to analyze the dependencies of runtimeClasspath only. I have tried the following methods:

- `DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: runtimeClasspath`, [log](https://github.com/Pil0tXia/eventmesh/actions/runs/8821707865), dependency graph artifact size: 563 Bytes (empty, no deps in it)
- `DEPENDENCY_GRAPH_EXCLUDE_CONFIGURATIONS: '.*[Tt]est(Compile|Runtime)Classpath'`, [log](https://github.com/Pil0tXia/eventmesh/actions/runs/8821717424), dependency graph artifact size: 18.2 KB (almost full deps in it, 18.3 KB when no exclusion applied)
- `DEPENDENCY_GRAPH_EXCLUDE_CONFIGURATIONS: '.*(testCompile|testRuntime|compile)Classpath'`, [log](https://github.com/Pil0tXia/eventmesh/actions/runs/8821840730), dependency graph artifact size: 16.8 KB (jupiter with testImplementation scope still in it although test exclusion declared)
- `DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: '[Ii]mplementation.*|[Rr]untime.*|[Cc]ompile.*|[Aa]pi.*|[Aa]nnotation.*'`, [log](https://github.com/Pil0tXia/eventmesh/actions/runs/8821920839), dependency graph artifact size: 10.9 KB (jupiter not in it finally, but lombok with compileOnly scope is still in it)
- `DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: '[Ii]mplementation.*|[Rr]untime.*|[Aa]pi.*'`, [log](https://github.com/Pil0tXia/eventmesh/actions/runs/8821949361), dependency graph artifact size: 563 Bytes (empty, no deps in it)

I am not clear about the reasons. I think I will temporarily use `DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: '[Ii]mplementation.*|[Rr]untime.*|[Cc]ompile.*|[Aa]pi.*'` to analyze the dependencies of runtimeClasspath (i.e., the dependencies bundled when packaging as a binary release), but `compileOnly` scope deps are not excluded with this regex.

**Comment by bigdaz** [comment]
Since this is a public project, I strongly recommend that you publish Build Scans for your dependency submission actions. This will give you a good overview of which configurations are _resolving_ the dependencies in question. It's difficult to get this sort of overview otherwise, since the way dependencies are declared and how they are resolved is different.

Another mechanism is to run the `dependencies` for each subproject in your project, since this task only reports on resolvable configurations.

Note that configurations named `implementation` and `api` are not resolvable.

**Comment by bigdaz** [comment]
I'd also recommend that you use the `dependency-submission` action to generate the dependency graph, since this will attempt to resolve _all_ resolvable configurations by default. 

Instead, you're generating a dependency graph based on running the `clean assemble compileTestJava` tasks: since you're not running the tests I suspect this doesn't require the `*[rR]untimeClasspath` configurations to be resolved at all. That would explain the empty graph when trying to include this configuration!

**Comment by Pil0tXia** [comment]
Great! I tired to use `dependency-submission` instead of `setup-gradle`, it works exactly what I want with `DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: '[rR]untimeClasspath'` ([log](https://github.com/Pil0tXia/eventmesh/actions/runs/8827124605)). Thanks a lot.

It seems that the deps generated by `setup-gradle` depends on its task, and `runtimeOnly` deps are only available in `build` task.

However, `DEPENDENCY_GRAPH_EXCLUDE_CONFIGURATIONS: '[tT]estCompileClasspath|[tT]estRuntimeClasspath|[cC]ompileClasspath'` doesn't have any effect ([log](https://github.com/Pil0tXia/eventmesh/actions/runs/8827163543)).

**Comment by bigdaz** [comment]
Did you try generating a build scan? If you share that I can help explain why you're seeing this behaviour. Without it I'm just guessing.

**Comment by Pil0tXia** [comment]
@bigdaz I'll try to generate one maybe tomorrow and then I'll update it under this post. 😊

**Comment by bigdaz** [comment]
I see now that [Develocity (Gradle Enterprise) is already enabled for `apache/eventmesh`](https://github.com/apache/eventmesh/blob/master/.github/workflows/codeql.yml#L65). All you need to do is supply the access key when running the `dependency-submission` action.

I really recommend you do that, so that you'll get Build Scans for each workflow run on an ongoing basis. However, since you won't have the access key configured in your fork, you won't be able to publish build scans to ge.apache.org until the code is merged. 

So for now, try re-running your PR workflow with action debugging enabled. The process is described here: https://github.com/gradle/actions/blob/main/docs/dependency-submission.md#when-you-cannot-publish-a-build-scan. This will tell you which dependencies are resolved in which configurations.

**Comment by Pil0tXia** [comment]
@bigdaz 

Thank you for instruction. I've re-ran [the job](https://github.com/Pil0tXia/eventmesh/actions/runs/8827163543/job/24381981697) with the `DEPENDENCY_GRAPH_EXCLUDE_CONFIGURATIONS: '[tT]estCompileClasspath|[tT]estRuntimeClasspath|[cC]ompileClasspath'` exclusion ([log](https://github.com/gradle/actions/files/15151546/logs_23128483743.zip)) and [the job](https://github.com/Pil0tXia/eventmesh/actions/runs/8827124605/job/24383500579) with the `DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: '[rR]untimeClasspath'` exclusion ([log](https://github.com/gradle/actions/files/15152340/logs_23128392601.zip)).

I briefly compared the logs of the two and it seems that only the latter outputs the following log:

```
Excluding resolved configuration from dependency graph: ...
```

**Comment by Pil0tXia** [comment]
@bigdaz Thanks for the analysis. That is, `detachedConfiguration` reintroduces the dependencies I want to exclude. So maybe using `DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS` is the best practice?

**Comment by bigdaz** [comment]
I'm not sure it's "best practice". The Spring Dependency Management plugin introduces a bunch of `detachedConfiguration` instances: perhaps one for every dependency you have declared? 
It's up to you if you want to selectively include or excluded, but I'd probably choose to exclude these `detachedConfiguration` instances. You risk missing more actual dependencies if you selectively include.

**Comment by bigdaz** [comment]
@Pil0tXia Are you OK with closing this issue? It would be great if you reply with a solution that works for you.

**Comment by Pil0tXia** [comment]
Since my purpose of using Dependency Gragh is to review third-party dependency licenses in binary distributions in conjunction with `dependency-review-action`, `include` would probably be more suitable for my scenario.

However, this solution is not applicable due to an [unresolved bug](https://github.com/actions/dependency-review-action/issues/632#issuecomment-2074252746) of `dependency-review-action`.
