### ISSUE TITLE
Cache cleanup should use the same Gradle executable as the build

### ISSUE THREAD

**Issue by msfjarvis** [gradle/actions#203]
The cache cleanup code here directly invokes Gradle from `$PATH`

https://github.com/gradle/actions/blob/90f1de055606f0041bed57fdbee974a43650e639/sources/src/caching/cache-cleaner.ts#L45

This can fail in some situations, such as using a Gradle RC release to gain support for running on a newer JDK. Here's a sample run demonstrating this exact situation: https://github.com/msfjarvis/compose-lobsters/actions/runs/8884243003/job/24392888298#step:10:25

My build is configured to run on JDK 22 and is using Gradle 8.8-RC1 but invoking Homebrew's Gradle fails because Gradle 8.7 is incompatible with JDK 22.

**Comment by bigdaz** [comment]
Using the version that invoked the build isn't going to work for a couple of reasons:
- A single job can run multiple versions of Gradle: these will all populate the same Gradle User Home.
- The cache-cleanup functionality in older versions of Gradle is inadequate. In fact Gradle 8.8 includes new cleanup features that make things much better, and we'll switch to use them as soon as 8.8 final is released.

The plan is to provision a Gradle version specifically to perform cache cleanup, rather than rely on the installed version. This will fix #33. But you make a good point that we'll need to ensure a compatible version of Java is used as well.

**Comment by bigdaz** [comment]
Closing as this will be addressed by #33
