### ISSUE TITLE
dependency-submissoin fails job even with upgraded dependencies

### ISSUE THREAD

**Issue by ccureau** [gradle/actions#206]
We are running into a situation where the dependency submission is failing, even though the gradle dependencies map shows that the package in question has automatically been replaced with a later version. 

As an example:

```
+--- org.apache.avro:avro:1.11.3
|    +--- com.fasterxml.jackson.core:jackson-core:2.14.2 -> 2.15.4 (*)
|    +--- com.fasterxml.jackson.core:jackson-databind:2.14.2 -> 2.15.4 (*)
|    +--- org.apache.commons:commons-compress:1.22 -> 1.26.1
|    |    +--- commons-codec:commons-codec:1.16.1
|    |    +--- commons-io:commons-io:2.15.1
|    |    \--- org.apache.commons:commons-lang3:3.14.0 -> 3.13.0
|    \--- org.slf4j:slf4j-api:1.7.36 -> 2.0.13
```

Although there is a vulnerable dependency in `commons-compress:1.22`, it has been replaced with `1.26.1`. However, the build step still fails.

is this intentional behavior? If so, is there a workaround?

**Comment by bigdaz** [comment]
Can you please explain what you mean by "the build step still fails"? 
Does 
1) The dependency submission action fail, indicating a problem with the action itself, or 
2) Do you have some sort of failure due to the dependency vulnerability?

If the answer is 2, then please check if `commons-compress:1.22` is present in the [Dependency Graph](https://github.com/gradle/github-dependency-submission-demo/blob/main/README.md#viewing-all-dependencies-for-this-repository) for your repository. If it appears in the dependency graph then it is very likely that the version is still being resolved in your build.

Please check out [this FAQ](https://github.com/gradle/actions/blob/main/docs/dependency-submission-faq.md#my-repository-dependency-graph-contains-a-dependency-that-isnt-anywhere-in-my-build-why-is-the-dependency-submission-action-reporting-dependencies-im-not-using) and [the documentation](https://github.com/gradle/actions/blob/main/docs/dependency-submission.md#finding-the-source-of-a-dependency-vulnerability) on how to resolve this.

**Comment by agsimeonov** [comment]
@bigdaz The issue is that it is failing due to a dependency vulnerability and the dependency graph seems to think that `org.apache.commons:commons-compress:1.22` is still available whereas it is not. 

When we generate the graph via gradle locally we see the following:
```
org.apache.commons:commons-compress:1.22 -> 1.26.1
```
This is stating that the transitive dependency has been upgraded from `1.22` to `1.26.1` which is the desired behavior to avoid the vulnerability.

When inspecting at the actual dependencies the project has pulled locally we no longer see `1.22` present at all.

We follow the official gradle documentation to achieve this by adding a constraint as so:
https://docs.gradle.org/current/userguide/dependency_constraints.html
```
implementation("org.apache.avro:avro:1.11.3")
constraints {
    implementation("org.apache.commons:commons-compress:1.26.1") {
        because("previous versions impacted by: https://github.com/advisories/GHSA-4265-ccf5-phj5")
    }
}
```

Unless I am missing something the dependency graph seems to ignore this which is the issue at hand.

**Comment by bigdaz** [comment]
Please check if commons-compress:1.22 is present in the [Dependency Graph](https://github.com/gradle/github-dependency-submission-demo/blob/main/README.md#viewing-all-dependencies-for-this-repository) for your repository. If it appears in the dependency graph then it is very likely that the version is still being resolved in your build.

Please check out [this FAQ](https://github.com/gradle/actions/blob/main/docs/dependency-submission-faq.md#my-repository-dependency-graph-contains-a-dependency-that-isnt-anywhere-in-my-build-why-is-the-dependency-submission-action-reporting-dependencies-im-not-using) and [the documentation](https://github.com/gradle/actions/blob/main/docs/dependency-submission.md#finding-the-source-of-a-dependency-vulnerability) on how to resolve this.

**Comment by bigdaz** [comment]
@ccureau @agsimeonov If you're unable to provide evidence that the action is submitting dependencies that are not being resolved by your build, I'll close this issue.

Please review the docs I linked and provide log output, build scan or something that shows the wrong dependencies are being submitted.
