### ISSUE TITLE
Validate wrappers for all Gradle nightlies published at https://services.gradle.org/distributions-snapshots/

### ISSUE THREAD

**Issue by eskatos** [gradle/actions#281]
This is a prerequisite for using the action in any repository that makes use of nightlies.

This is a prerequisite for dogfooding in the `gradle` org which makes heavy use of nightlies.

Currently, the action consumes https://services.gradle.org/versions/all which contains information about the latest nightly and the latest release nightly only. All other nightlies are missing.

**Comment by 3flex** [comment]
The services.gradle.org versions API only provides details on latest nightly (and release nightly), so wouldn't the API need to be enhanced first? Is there another source for this?

**Comment by bigdaz** [comment]
While not ideal, it should be possible to extract the wrapper checksums by traversing the directory listing at https://services.gradle.org/distributions-snapshots/

**Comment by 3flex** [comment]
Do you mean by reading the HTML and looking for the links? Or is there another way? I'd have thought that would be a little fragile, and failures to parse would have to fail the action if validation has been enabled (though given it's for nightlies failures are relatively lower impact, and any issue would surely be fixed quickly especially if it's impacting Gradle's own builds).

I'm not volunteering to build a PR since I'm unfamiliar with TypeScript but the pointers might help someone with the right experience. It would be nice to unblock #12 for v4.

**Comment by bigdaz** [comment]
Yes, that's what I meant. The HTML is a generated directory listing and should be generally stable over time.

We would only fail the build if all of the following were true:
- Wrapper jar is NOT in the set of known checksums hard-coded into the action. These hardcoded values represent what was in https://services.gradle.org/versions/all at the time of release.
- Wrapper jar is NOT found currently in https://services.gradle.org/versions/all, or we fail to read from that source. Any Gradle versions released since `gradle/actions` was released should be present here.
- Wrapper jar is NOT found in https://services.gradle.org/distributions-snapshots, or we fail to read from that source.

I think this would be acceptable.

I'm not sure about getting #14 into `v4`, but you're right that it would be nice.
I now wish I'd released `v4.0.0-beta.1` instead of going straight to an RC!
