### ISSUE TITLE
Paths in `gradle-home-cache-excludes` are not honoured when restoring Gradle User Home from cache

### ISSUE THREAD

**Issue by ribafish** [gradle/actions#296]
The `setup-gradle` action offers a way to exclude paths from being cached in the gradle user home with the input of `gradle-home-cache-excludes`. Currently this only prevents the paths defined to not be cached, however if the paths have been cached previously already (or in a different action) they will still get expanded. I would expect that the input of `gradle-home-cache-excludes` would also prevent expansion of paths defined in the exclude.

[This is an example](https://github.com/gradle/android-cache-fix-gradle-plugin/actions/runs/9954299921/job/27499628200#step:4:4) setup of gradle-setup action mean that I'd expect defined paths aren't restored from cache, however as seen [here, they are still expanded.](https://github.com/gradle/android-cache-fix-gradle-plugin/actions/runs/9954299921/job/27499628200#step:4:81)

**Comment by bigdaz** [comment]
@ribafish I think this should be fixed now. Can you please test using `gradle/actions/setup-gradle@main`?

The log entry you linked will still be present since the entries will still be expanded. This is required because the exclude paths may be a subdir or parent-dir of a restored entry. But now the excluded paths will be deleted immediately after restoring. You should be able to check if the files exist using a `run` command immediate after the `setup-gradle` step.

**Comment by bigdaz** [comment]
@ribafish The fix is now in the v4 release candidate.

If you could test it out using `gradle/actions/setup-gradle@v4.0.0-rc.1` that would be helpful.

**Comment by ribafish** [comment]
@bigdaz Looks like this is now fixed with `v4.0.0-rc.1`. Here are two runs: One without [any excludes (seed/baseline)](https://github.com/ribafish/oldGeReproducer/actions/runs/10096364215/job/27919141837#step:5:26) and the [second with the excludes](https://github.com/ribafish/oldGeReproducer/actions/runs/10096319715/job/27918540824#step:5:25) (for example the `caches/build-cache-1`), which does not have the paths set as excludes.
