### ISSUE TITLE
dependabot creates pull requests for version 4

### ISSUE THREAD

**Issue by tobias-kleinschmidt-fnt** [gradle/actions#322]
dependabot is creating pull requests in our projects to update the gradle/actions action from version 3 to version 4 although only a pre-release is available. dependabot might be reacting to your "v4" git tag? I really don't want to update our build pipelines to a pre-release version of this action. :-)

**Comment by TWiStErRob** [comment]
Same with Renovate. They don't know it's RC, because it's just `@v3` to `@v4`, a simple major bump.

The only "solution" is not merging the PR until it's actually released. But everyone who uses the action will have to understand what's going on here, which is a lot of cognitive hours around the world :D

**Comment by bigdaz** [comment]
I think the ship has sailed :).
Being a release candidate, I don't know of any issues that need addressing for the final release. Barring any new reports I plan on releasing `v4.0.0` in the next couple of days.

**Comment by Marcono1234** [comment]
v4.0.0 has been released now, so this issue can probably be closed, right?

**Comment by bigdaz** [comment]
Yep, closing it now.
