### ISSUE TITLE
Could not load from local cache: Timeout waiting to lock Build cache

### ISSUE THREAD

**Issue by fpiresca** [gradle/actions#325]
Hello there! 

I am running into a process deadlocks with gradle cache folder from time to time. I am trying to run a matrix build with two different versions, and if the job lands on the same machine (using self-hosted runners) the job that starts late won't complete. 

`Caused by: org.gradle.caching.internal.controller.BuildCacheOperationException: Could not load from local cache: Timeout waiting to lock Build cache (/.gradle/caches/build-cache-1). It is currently in use by another Gradle instance.`

Is there another way of fixing this without disabling matrix builds all together?

**Comment by bigdaz** [comment]
Thanks for the report.
Can you able to share more details about your setup? (Ideally a link to the GitHub Actions run)

- What operating System?
- Do you have 2 jobs running on the same runner at the same time? Or are these running sequentially?
- Are the jobs running in Docker containers on the runner?
- Any other details about your setup?

I've seem similar issues before when 2 Gradle executions run simultaneously in separate Docker containers and share the same Gradle User Home directory.

**Comment by fpiresca** [comment]
**What operating System?**
MacOS Sonoma
**Do you have 2 jobs running on the same runner at the same time? Or are these running sequentially?**
Using Matrix Build they run at the same time. 

Are the jobs running in Docker containers on the runner?
No docker, but they share the .gradle folder when the jobs lands on the same machine we have two mac machines. 

Can you see the Gradle daemon being stopped at the end of each Job (in the GHA logs)?
Yes, I am seeing that the process is getting terminated at the end of the run.

**Comment by bigdaz** [comment]
> **What operating System?** MacOS Sonoma **Do you have 2 jobs running on the same runner at the same time? Or are these running sequentially?** 
Using Matrix Build they run at the same time.

Correct, but the usual case is that a runner will only execute a single job at a time, so the matrix jobs will be distributed across 2 runners.

> **Are the jobs running in Docker containers on the runner?** 
> No docker, but they share the .gradle folder when the jobs lands on the same machine we have two mac machines.

OK, it seems the issue is unrelated to the `setup-gradle` action, and is more of a problem with 2 concurrent Gradle builds on the same machine.

See [this issue](https://github.com/gradle/gradle/issues/8375) for example.

A few things you could try:
- Disable the local build cache for these Gradle builds. (Add `--no-build-cache` to the CLI args)
- Use separate Gradle User Home directories for different Jobs running simultaneously. For example set the env var `GRADLE_USER_HOME=$GITHUB_WORKSPACE/.gradle`
- Avoid running 2 GitHub Actions jobs simultaneously on the same runner. This is the default for GitHub hosted runners

**Comment by fpiresca** [comment]
Thank you for the advice, I'll change the GRADLE_USER_HOME and update it here if works well.
