### ISSUE TITLE
Some dependencies seem to be captured twice

### ISSUE THREAD

**Issue by oleg-nenashev** [gradle/actions#63]
For a single build, it looks like some of the dependencies are captured twice with different versions

![image](https://github.com/gradle/actions/assets/3000480/245862c4-f3eb-44fe-86fc-71888fa1e4bc)

## Reproduction

Run project/pipeline from https://github.com/oleg-nenashev/gradle-quarkus-plugin-demo/commit/109b203b7dd039db603c1ca677a66767e01202d7

**Comment by bigdaz** [comment]
This is almost certainly because the dependency _is actually being resolved_ with different versions in different dependency configurations.

[See here for a HOW-TO](https://github.com/gradle/actions/blob/main/dependency-submission/README.md#resolving-a-dependency-vulnerability) on getting the bottom of why the dependency is being resolved. By far the easiest way is to publish a Build Scan® for the workflow run: [this is easily achieved with some additional action configuration](https://github.com/gradle/actions/blob/main/dependency-submission/README.md#publishing-a-develocity-build-scan-from-your-dependency-submission-workflow).

**Comment by bigdaz** [comment]
This is not a problem with dependency-submission: your project is indeed resolving the same dependencies with multiple versions.

[See here](https://scans.gradle.com/s/4h2g7klhe47zu/dependencies?dependencies=io.quarkus.arc:arc&expandAll) that `io.quarkus.arc:arc` is being resolved with both `3.8.1` and `3.8.2`.

[See here](https://scans.gradle.com/s/4h2g7klhe47zu/dependencies?dependencies=io.quarkus.resteasy.reactive:resteasy-reactive&expandAll) that `io.quarkus.resteasy.reactive:resteasy-reactive-*` modules are being resolved with both `3.5.3` and `3.8.2`.

Whether this is desired is a different matter: the `dependency-submission` action is accurately submitting the set of dependencies resolved.

**Comment by oleg-nenashev** [comment]
Ack, thanks!
