### ISSUE TITLE
setup-gradle: ./gradlew: No such file or directory

### ISSUE THREAD

**Issue by davidkhala** [gradle/actions#84]
I see a critial error in my first try using `setup-gradle`
```
./gradlew: No such file or directory
```

The error scenario and logs sits in 
https://github.com/davidkhala/java-common/actions/runs/8387290539/job/22969204674

Please let me know if it is known issue.

**Comment by bigdaz** [comment]
In [this line of your workflow](https://github.com/davidkhala/java-common/actions/runs/8387290539/workflow#L14), you are calling `./gradlew build`. This only works if you have the [Gradle Wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html) configured for your project.

Otherwise, you can simply call `gradle build` which will use the latest version of Gradle to build your project. [You can choose a different Gradle version](https://github.com/gradle/actions/tree/main/setup-gradle#choose-a-specific-gradle-version) if required.

**Comment by davidkhala** [comment]
@bigdaz Thanks for pointing me out the solution, but the issue is the current `README.md` doesn't mention that, I would like to create a PR based on this.

**Comment by davidkhala** [comment]
And according to this README
https://github.com/gradle/actions/blob/main/setup-gradle/README.md

The `wrapper` options should be default as documented. But it doesn't work as expected.
