### ISSUE TITLE
⏳ Long setup on Windows

### ISSUE THREAD

**Issue by LVMVRQUXL** [gradle/actions#92]
Using `gradle/actions/setup-gradle@v3.1.0`, the setup of Gradle takes more than 5 minutes on Windows.
Here's an example of a [job in GitHub Action](https://github.com/kotools/types/actions/runs/8499075333/job/23279506444) that took **10m 43s**, including **7m 10s** just for using this action.

**Comment by LVMVRQUXL** [comment]
@bigdaz Thank you for the detailed informations about this issue.
The Windows job with the suggested environment variable set is available [here](https://github.com/kotools/types/actions/runs/8512953322/job/23315673690).
Do you have any fix or workaround in mind for resolving this problem?

**Comment by bigdaz** [comment]
Thanks. I suspect that the underlying issue is that your [restored Gradle User Home is quite large](https://github.com/kotools/types/actions/runs/8512953322/job/23315673690#step:4:378), and the combined [caches/8.6/kotlin-dsl](https://github.com/kotools/types/actions/runs/8512953322/job/23315673690#step:4:223) and [caches/8.7/kotlin-dsl](https://github.com/kotools/types/actions/runs/8512953322/job/23315673690#step:4:265) directories are over 600Mb after extracting (even though the compressed size is around 10Mb!). It's possible that extracting the 10Mb tarball to 600Mb is taking an inordinate amount of time on Windows.

Can you please run the build again, this time with [ACTION_STEP_DEBUG logging enabled](https://github.com/gradle/actions/blob/main/setup-gradle/README.md#debugging-and-troubleshooting)? This should produce some additional logging from within the `actions/cache` library.

**Comment by LVMVRQUXL** [comment]
@bigdaz Like requested, here is [the latest attempt of the Windows job](https://github.com/kotools/types/actions/runs/8512953322/job/23383334425) with the debug logging enabled.

**Comment by bigdaz** [comment]
Thanks. The [log output](https://productionresultssa10.blob.core.windows.net/actions-results/38107adf-8186-42b8-8a8a-e8fc732a918a/workflow-job-run-b6b3ff93-324a-58af-7add-8d893e6648cb/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-04-03T14%3A24%3A33Z&sig=QrMTh0LPKrG8dH2BzJFzabiwNKVlHYPLPMA6Bxw%2BeZo%3D&sp=r&spr=https&sr=b&st=2024-04-03T14%3A14%3A28Z&sv=2021-12-02) confirms that you have a very large number of files in the `kotlin-dsl` cache entry. This adds to my suspicion that extracting the giant tarball on Windows is very slow.

Yes, enabling [gradle-home-cache-cleanup](https://github.com/gradle/actions/blob/main/setup-gradle/README.md#remove-unused-files-from-gradle-user-home-before-saving-to-the-cache) should help to mitigate this issue, since any unused files in `kotlin-dsl` should be purged. Please try it out and let us know the impact.

**Comment by bigdaz** [comment]
Alternatively, you could manually delete the [kotlin-dsl cache entries](https://github.com/kotools/types/actions/caches).

**Comment by LVMVRQUXL** [comment]
I think that enabling the [Gradle home cache cleanup](https://github.com/gradle/actions/blob/main/setup-gradle/README.md#remove-unused-files-from-gradle-user-home-before-saving-to-the-cache) really helped: [my latest attempt on Windows](https://github.com/kotools/types/actions/runs/8551832792/job/23437349984) now took 4m46 for setting up Gradle! 🙌

Thank you for your help @bigdaz! 🙏

I let you close this issue if not needed anymore. 😁

**Comment by bigdaz** [comment]
Thanks for the report, and glad you see improvement. Ideally it would take a lot less than 5min to restore your Gradle User Home, and it [still seems to be taking a very long time](https://github.com/kotools/types/actions/runs/8551832792/job/23437349984#step:4:151) restoring the `kotlin-dsl` entry.

But I don't think there's much we can do in the action to improve this situation. So I'm going to close this issue for now.

**Comment by LVMVRQUXL** [comment]
I may try to simplify the overall workflow by only running jobs on Ubuntu instead, [which is way more faster than Windows](https://github.com/kotools/types/actions/runs/8551832792/job/23437349731).
But I don't know if it is possible to run Kotlin Native tests targeting Windows on Ubuntu. 👀
